<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2021-05-01T09:32:14" hostname="wangweilideMBP.lan" time="0.119">
  <properties/>
  <testcase name="clearFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.044"/>
  <testcase name="evictFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.009"/>
  <testcase name="getFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.008"/>
  <testcase name="putFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.008"/>
  <testcase name="getFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.009"/>
  <testcase name="getAndPutFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.012"/>
  <testcase name="putFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.01"/>
  <testcase name="evictFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.009"/>
  <testcase name="clearFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.008"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
